# ********RoostGPT********

# Test generated by RoostGPT for test test-workflow using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /pet/findByTags_get for http method type GET 
# RoostTestHash=01adc2ed1e
# 
# 

# ********RoostGPT********
Feature: Testing /v2/pet/findByTags endpoint

Background:
  * url target
  * def auth = { token: '#(authToken)' }
  * configure headers = auth

Scenario: Find pets by tags
  Given path 'v2/pet/findByTags'
  And param tags = ['pet']
  When method get
  Then status 200
  And match response contains {name: '#string', photoUrls: '#[]'}
  And match each response contains {id: '#number', name: '#string', photoUrls: '#[]', tags: '#[]', status: '#string'}
  And match responseHeaders contains { 'Content-Type': 'application/json' }

Scenario: Invalid tag value
  Given path 'v2/pet/findByTags'
  And param tags = ['invalid']
  When method get
  Then status 400
