# ********RoostGPT********

# Test generated by RoostGPT for test test-workflow using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /store/inventory_get for http method type GET 
# RoostTestHash=a66f7079af
# 
# 

# ********RoostGPT********
Feature: Store Inventory API

  Background:
    * url target
    * def auth = { Authorization: '#(authToken)' }
    * configure headers = auth

  @getInventory
  Scenario: Returns pet inventories by status
    Given path '/v2/store/inventory'
    When method get
    Then status 200
    And match response == { "type": "object", "additionalProperties": { "type": "integer", "format": "int32" } }
