# ********RoostGPT********

# Test generated by RoostGPT for test test-workflow using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /user/logout_get for http method type GET 
# RoostTestHash=696422fb14
# 
# 

# ********RoostGPT********
Feature: User Logout API

  Background:
    * url target
    * header Authorization = $processEnvironment.AUTH_TOKEN

  Scenario: Verify user can successfully logout

    Given path '/v2/user/logout'
    When method post
    Then status 200
    And match response == {description: 'successful operation'}

  Scenario: Verify response when user is not logged in

    Given path '/v2/user/logout'
    When method post
    Then status 401
    And match response == {description: 'User not logged in'}

  Scenario: Verify response when invalid token is used

    Given path '/v2/user/logout'
    And header Authorization = 'InvalidToken'
    When method post
    Then status 403
    And match response == {description: 'Invalid token'}
