# ********RoostGPT********

# Test generated by RoostGPT for test test-workflow using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /store/order_post for http method type POST 
# RoostTestHash=8153b7f54d
# 
# 

# ********RoostGPT********
Feature: Test /v2/store/order API

Background:
  * url target
  * def authToken = $processEnvironment.AUTH_TOKEN
  * configure headers = { Authorization: '#(authToken)' }

Scenario: Validate successful operation when placing an order for a pet
  Given path '/v2/store/order'
  And request
  """
  {
    "id": 1,
    "petId": 1,
    "quantity": 1,
    "shipDate": "2022-12-12T12:12:12.000Z",
    "status": "placed",
    "complete": false
  }
  """
  When method post
  Then status 200
  And match response ==
  """
  {
    "id": 1,
    "petId": 1,
    "quantity": 1,
    "shipDate": "2022-12-12T12:12:12.000Z",
    "status": "placed",
    "complete": false
  }
  """

Scenario: Validate Invalid Order error when placing an order with invalid data
  Given path '/v2/store/order'
  And request
  """
  {
    "id": "invalid",
    "petId": 1,
    "quantity": 1,
    "shipDate": "2022-12-12T12:12:12.000Z",
    "status": "placed",
    "complete": false
  }
  """
  When method post
  Then status 400
