# ********RoostGPT********

# Test generated by RoostGPT for test test-workflow using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /store/order/{orderId}_get for http method type GET 
# RoostTestHash=cd8cc54cf7
# 
# 

# ********RoostGPT********
Feature: Test /v2/store/order/{orderId} API

Background:
  * url target

Scenario: Test GET /v2/store/order/{orderId} API with valid orderId
  * def authToken = $processEnvironment.AUTH_TOKEN
  * def headers = { Authorization: '#(authToken)' }
  * path '/v2/store/order/{orderId}'
  * method get
  * status 200

Examples:
  | orderId |
  | 1       |
  | 2       |
  | 3       |
  | 4       |
  | 5       |
  | 6       |
  | 7       |
  | 8       |
  | 9       |
  | 10      |

Scenario: Test GET /v2/store/order/{orderId} API with invalid orderId
  * def authToken = $processEnvironment.AUTH_TOKEN
  * def headers = { Authorization: '#(authToken)' }
  * path '/v2/store/order/{orderId}'
  * method get
  * status 400

Examples:
  | orderId |
  | 0       |
  | 11      |
  | -1      |
  | 'abc'   |

Scenario: Test GET /v2/store/order/{orderId} API with non-existent orderId
  * def authToken = $processEnvironment.AUTH_TOKEN
  * def headers = { Authorization: '#(authToken)' }
  * path '/v2/store/order/{orderId}'
  * method get
  * status 404

Examples:
  | orderId |
  | 100     |
  | 200     |
  | 300     |
  | 400     |
  | 500     |
