# ********RoostGPT********

# Test generated by RoostGPT for test test-workflow using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /store/order/{orderId}_delete for http method type DELETE 
# RoostTestHash=36caaf0283
# 
# 

# ********RoostGPT********
Feature: Test /v2/store/order/{orderId} endpoint

Background:
* url target
* def authToken = karate.properties['AUTH_TOKEN']
* configure headers = {Authorization: '#(authToken)'}

Scenario: Delete purchase order by ID with valid orderId
    Given path '/v2/store/order/', 1
    When method delete
    Then status 200
    And match response == {message: 'Order deleted successfully'}

Scenario: Delete purchase order by ID with invalid orderId
    Given path '/v2/store/order/', 'invalid'
    When method delete
    Then status 400
    And match response == {message: 'Invalid ID supplied'}

Scenario: Delete purchase order by ID with non-existing orderId
    Given path '/v2/store/order/', 9999
    When method delete
    Then status 404
    And match response == {message: 'Order not found'}
