# ********RoostGPT********

# Test generated by RoostGPT for test test-workflow using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /pet/{petId}_get for http method type GET 
# RoostTestHash=018c365850
# 
# 

# ********RoostGPT********
Feature: Find pet by ID API test

  Background:
    * url target
    * def auth = { Authorization: '#(authToken)' }
    * configure headers = auth

  Scenario Outline: Test Find pet by ID API with valid petId
    Given path 'v2/pet/', <petId>
    When method get
    Then status 200
    And match response == { id: '#number', category: '#object', name: '#string', photoUrls: '#array', tags: '#array', status: '#string' }

  Scenario Outline: Test Find pet by ID API with invalid petId
    Given path 'v2/pet/', <petId>
    When method get
    Then status 400

  Scenario Outline: Test Find pet by ID API with petId not found
    Given path 'v2/pet/', <petId>
    When method get
    Then status 404

  Examples:
    | petId |
    | 1234  |
    | abc   |
    | 9999  |
