# ********RoostGPT********

# Test generated by RoostGPT for test test-workflow using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /pet/{petId}_post for http method type POST 
# RoostTestHash=c0bc5294a0
# 
# 

# ********RoostGPT********
Feature: Petstore API Tests

Background:
    * url target
    * header Authorization = 'Bearer ' + $processEnvironment.AUTH_TOKEN

Scenario: Update a pet in the store with form data
    Given path '/v2/pet/', '#(petId)'
    And form field name = '#(name)'
    And form field status = '#(status)'
    When method put
    Then status 200
    And match responseHeaders['Content-Type'] == 'application/json'
    And match response == {id:'#(petId)', name:'#(name)', status:'#(status)'}

Examples:
| petId | name   | status   |
| 1234   | 'Bobby' | 'available' |
| 5678   | 'Tommy' | 'sold'      |
