# ********RoostGPT********

# Test generated by RoostGPT for test test-workflow using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /pet/{petId}/uploadImage_post for http method type POST 
# RoostTestHash=8dac89cb33
# 
# 

# ********RoostGPT********
Feature: Petstore API

Background:
  * url target: '{{ $processEnvironment.API_HOST }}'
  * def authToken = '{{ $processEnvironment.AUTH_TOKEN }}'
  * configure headers = { Authorization: '#(authToken)' }

Scenario: Upload an image for a pet
  Given path '/v2/pet/{petId}/uploadImage'
  And multipart file file = { read: 'path_to_file', filename: 'file_name', contentType: 'image/jpeg' }
  And multipart field additionalMetadata = 'Additional data'
  When method post
  Then status 200
  And match response == { code: '#number', type: '#string', message: '#string' }
