# ********RoostGPT********

# Test generated by RoostGPT for test test-workflow using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /user_post for http method type POST 
# RoostTestHash=d815599fc6
# 
# 

# ********RoostGPT********
Feature: User API

Background:
  * url target: '{{ $processEnvironment.API_HOST }}'
  * def auth = { Authorization: 'Bearer ' + $processEnvironment.AUTH_TOKEN }

Scenario: Create a new user
  Given path '/v2/user'
  And request {"id": 1,"username": "testUser","firstName": "Test","lastName": "User","email": "testUser@example.com","password": "password","phone": "1234567890","userStatus": 1}
  And headers auth
  When method post
  Then status 200
  And match response == {"description":"successful operation"}
  And match responseHeaders['Content-Type'][0] == 'application/json'

Examples:
  | id | username  | firstName | lastName | email               | password | phone      | userStatus |
  | 1  | testUser  | Test      | User     | testUser@example.com| password | 1234567890 | 1          |
  | 2  | testUser2 | Test2     | User2    | testUser2@example.com| password2 | 1234567891 | 2          |
