# ********RoostGPT********

# Test generated by RoostGPT for test test-workflow using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /user/{username}_delete for http method type DELETE 
# RoostTestHash=5caa5e3efb
# 
# 

# ********RoostGPT********
Feature: Testing DELETE user endpoint

Background:
  * url target
  * def authToken = karate.env == 'e2e' ? karate.properties['authToken'] : karate.properties['authToken']

Scenario: Delete user - Invalid username supplied
  Given path '/v2/user/{username}'
  And header Authorization = authToken
  When method delete
  Then status 400
  And match response == { description: 'Invalid username supplied' }

Scenario: Delete user - User not found
  Given path '/v2/user/{username}'
  And header Authorization = authToken
  When method delete
  Then status 404
  And match response == { description: 'User not found' }

Examples:
| username |
| 'test1'  |
| 'test2'  |
| 'test3'  |
