# ********RoostGPT********

# Test generated by RoostGPT for test test-workflow using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /user/{username}_put for http method type PUT 
# RoostTestHash=ec22222bac
# 
# 

# ********RoostGPT********
Feature: User API

Background:
* url target
* header Authorization = 'Bearer ' + $processEnvironment.AUTH_TOKEN

Scenario: Update existing user

Given path '/v2/user/', '#(username)'
And request
"""
{
  "id": 1,
  "username": "newUsername",
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "password": "password",
  "phone": "1234567890",
  "userStatus": 1
}
"""
When method put
Then status 200
And match response ==
"""
{
  "id": 1,
  "username": "newUsername",
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "password": "password",
  "phone": "1234567890",
  "userStatus": 1
}
"""

Examples:
| username |
| 'oldUsername' |
