# ********RoostGPT********

# Test generated by RoostGPT for test test-workflow using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /user/{username}_get for http method type GET 
# RoostTestHash=b96457affd
# 
# 

# ********RoostGPT********
Feature: Testing /v2/user/{username} endpoint

Background:
  * url target
  * def authToken = karate.properties['AUTH_TOKEN']

Scenario: Get user by username
  Given path '/v2/user/{username}'
  And header Authorization = authToken
  When method get
  Then status 200
  And match response == { id: '#number', username: '#string', firstName: '#string', lastName: '#string', email: '#string', password: '#string', phone: '#string', userStatus: '#number' }

Examples:
  | username |
  | 'user1'  |

Scenario: Get user by invalid username
  Given path '/v2/user/{username}'
  And header Authorization = authToken
  When method get
  Then status 400

Examples:
  | username |
  | 'invalidUser' |

Scenario: Get user by non-existent username
  Given path '/v2/user/{username}'
  And header Authorization = authToken
  When method get
  Then status 404

Examples:
  | username |
  | 'nonExistentUser' |
