# ********RoostGPT********

# Test generated by RoostGPT for test artilleryTest using AI Type  and AI Model 
# 
# Feature file generated for /kafka/v3/clusters/{cluster_id}/topics/{topic_name}/partitions/{partition_id}_get for http method type GET 
# RoostTestHash=0ecd20dc17
# 
# 

# ********RoostGPT********
Feature: Karate API Testing

  Background:
    * def urlBase = karate.properties['alias_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario Outline: Get Partition - Valid Input
    Given path '/kafka/v3/clusters/{cluster_id}/topics/{topic_name}/partitions/{partition_id}'
    And path cluster_id = '<cluster_id>'
    And path topic_name = '<topic_name>'
    And path partition_id = <partition_id>
    When method GET
    Then status 200
    And match response == { "kind": "KafkaPartition", "metadata": { "self": "<self_url>", "resource_name": "<resource_name>" }, "cluster_id": "<cluster_id>", "topic_name": "<topic_name>", "partition_id": <partition_id>, "leader": { "related": "<leader_url>" }, "replicas": { "related": "<replicas_url>" }, "reassignment": { "related": "<reassignment_url>" } }

    Examples:
      | read('kafka_v3_clusters_cluster_id_topics_topic_name_partitions_partition_id_get.csv') |

  Scenario: Get Partition - Invalid Input
    Given path '/kafka/v3/clusters/{cluster_id}/topics/{topic_name}/partitions/{partition_id}'
    And path cluster_id = '<cluster_id>'
    And path topic_name = '<topic_name>'
    And path partition_id = <partition_id>
    When method GET
    Then status 400

  Scenario: Get Partition - Unauthorized
    Given path '/kafka/v3/clusters/{cluster_id}/topics/{topic_name}/partitions/{partition_id}'
    And path cluster_id = '<cluster_id>'
    And path topic_name = '<topic_name>'
    And path partition_id = <partition_id>
    When method GET
    Then status 401

  Scenario: Get Partition - Not Found
    Given path '/kafka/v3/clusters/{cluster_id}/topics/{topic_name}/partitions/{partition_id}'
    And path cluster_id = '<cluster_id>'
    And path topic_name = '<topic_name>'
    And path partition_id = <partition_id>
    When method GET
    Then status 404

  Scenario: Get Partition - Rate Limited
    Given path '/kafka/v3/clusters/{cluster_id}/topics/{topic_name}/partitions/{partition_id}'
    And path cluster_id = '<cluster_id>'
    And path topic_name = '<topic_name>'
    And path partition_id = <partition_id>
    When method GET
    Then status 429

  Scenario: Get Partition - Internal Server Error
    Given path '/kafka/v3/clusters/{cluster_id}/topics/{topic_name}/partitions/{partition_id}'
    And path cluster_id = '<cluster_id>'
    And path topic_name = '<topic_name>'
    And path partition_id = <partition_id>
    When method GET
    Then status 500
