# ********RoostGPT********

# Test generated by RoostGPT for test artilleryTest using AI Type  and AI Model 
# 
# Feature file generated for /kafka/v3/clusters/{cluster_id}/topics/{topic_name}/partitions_get for http method type GET 
# RoostTestHash=4ee5afee1b
# 
# 

# ********RoostGPT********
Feature: API Endpoint - /kafka/v3/clusters/{cluster_id}/topics/{topic_name}/partitions

  Background:
    * def urlBase = karate.properties['alias_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario: Get list of partitions
    Given path '/kafka/v3/clusters/{cluster_id}/topics/{topic_name}/partitions'
    And path cluster_id = 'cluster-1'
    And path topic_name = 'topic-1'
    When method GET
    Then status 200
    And match response == { kind: '#string', metadata: { self: '#string', next: '#null' }, data: '#array' }
