# ********RoostGPT********

# Test generated by RoostGPT for test artilleryTest using AI Type  and AI Model 
# 
# Feature file generated for /kafka/v3/clusters/{cluster_id}/topics_post for http method type POST 
# RoostTestHash=783e9d2ab5
# 
# 

# ********RoostGPT********
Feature: Create Topic

Background:
  * def urlBase = karate.properties['alias_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
  * url urlBase

Scenario: Create a topic with valid input payload
  Given path '/kafka/v3/clusters/{cluster_id}/topics'
  And request """
    {
      "topic_name": "<topic_name>",
      "partitions_count": "<partitions_count>",
      "replication_factor": "<replication_factor>",
      "configs": "<configs>",
      "validate_only": "<validate_only>"
    }
  """
  When method POST
  Then status 201
  And match response == {
    "kind": "KafkaTopic",
    "metadata": {
      "self": "#string",
      "resource_name": "#string"
    },
    "cluster_id": "#string",
    "topic_name": "#string",
    "is_internal": false,
    "replication_factor": "#number",
    "partitions_count": "#number",
    "partitions": {
      "related": "#string"
    },
    "configs": {
      "related": "#string"
    },
    "partition_reassignments": {
      "related": "#string"
    },
    "authorized_operations": [
      "UNKNOWN",
      "ALL",
      "READ",
      "WRITE",
      "CREATE",
      "DELETE",
      "ALTER",
      "DESCRIBE",
      "CLUSTER_ACTION",
      "DESCRIBE_CONFIGS",
      "ALTER_CONFIGS",
      "IDEMPOTENT_WRITE"
    ]
  }
