# ********RoostGPT********

# Test generated by RoostGPT for test artilleryTest using AI Type  and AI Model 
# 
# Feature file generated for /kafka/v3/clusters/{cluster_id}/topics_get for http method type GET 
# RoostTestHash=5a89adf6e3
# 
# 

# ********RoostGPT********
Feature: List Topics

  Background:
    * url urlBase

  Scenario Outline: List topics with valid input
    Given path '/kafka/v3/clusters/<cluster_id>/topics'
    And headers Authorization = 'Bearer <auth_token>'
    When method <http_method>
    Then status <response_code>
    And match response == <response_body>

    Examples:
      | cluster_id | http_method | response_code | response_body |
      |     123456 | GET         |           200 | {}            |
