# ********RoostGPT********

# Test generated by RoostGPT for test artilleryTest using AI Type  and AI Model 
# 
# Feature file generated for /kafka/v3/clusters/{cluster_id}/topics/{topic_name}_delete for http method type DELETE 
# RoostTestHash=b9526a5d59
# 
# 

# ********RoostGPT********
Feature: Delete Kafka Topic

  Background:
    * def urlBase = karate.properties['alias_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario: Delete a Kafka Topic
    Given path '/kafka/v3/clusters/{cluster_id}/topics/{topic_name}'
    And path cluster_id = '<cluster_id>'
    And path topic_name = '<topic_name>'
    And method DELETE
    When method DELETE
    Then status 204
    And assert responseStatus == 204
