# ********RoostGPT********

# Test generated by RoostGPT for test test-workflow using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /pet/findByTags_get for http method type GET 
# RoostTestHash=01adc2ed1e
# 
# 

# ********RoostGPT********
Feature: Test /v2/pet/findByTags API endpoint

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.properties['auth.token'] || karate.get('authToken')
  * configure headers = { Authorization: '#(authToken)' }

Scenario: Test GET method with valid tags
  Given path '/v2/pet/findByTags'
  And param tags = ['pet']
  When method get
  Then status 200
  And match response contains { "name": '#string', "photoUrls": '#[]' }

Scenario: Test GET method with invalid tags
  Given path '/v2/pet/findByTags'
  And param tags = ['invalidTag']
  When method get
  Then status 400

Scenario Outline: Test GET method with different tags
  Given path '/v2/pet/findByTags'
  And param tags = ['<tags>']
  When method get
  Then status <status_code>

  Examples:
    | tags           | status_code |
    | 'pet'          | 200         |
    | 'invalidTag'   | 400         |

