# ********RoostGPT********

# Test generated by RoostGPT for test test-workflow using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /pet/findByTags_get for http method type GET 
# RoostTestHash=01adc2ed1e
# 
# 

# ********RoostGPT********
Feature: Test /v2/pet/findByTags API endpoint

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.properties['auth.token'] || karate.get('authToken')
  * configure headers = { Authorization: '#(authToken)' }

Scenario: Test GET method with valid tags
  Given path '/v2/pet/findByTags'
  And param tags = ['pet']
  When method get
  Then status 200
  And match response contains {name:'#string', photoUrls:'#[]'}
  And match response[*].name == '#string'
  And match response[*].photoUrls == '#[]'
  And match response[*].tags == '#[]'
  And match response[*].status == '#string'

Scenario: Test GET method with invalid tags
  Given path '/v2/pet/findByTags'
  And param tags = ['invalid']
  When method get
  Then status 400

Examples:
  | tags       |
  | ['dog']    |
  | ['cat']    |
  | ['rabbit'] |
