# ********RoostGPT********

# Test generated by RoostGPT for test test-workflow using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /pet_post for http method type POST 
# RoostTestHash=988c5ab2ac
# 
# 

# ********RoostGPT********
Feature: Pet Store Management

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * def headers = { 'Authorization': '#(authToken)' }
  
  Scenario: Add a new pet to the store
    Given path '/v2/pet'
    And request { "id": #(id), "category": { "id": #(categoryId), "name": '#(categoryName)' }, "name": '#(name)', "photoUrls": '#(photoUrls)', "tags": '#(tags)', "status": '#(status)' }
    And headers headers
    When method post
    Then status 200
    And match response == { "id": '#(id)', "category": { "id": '#(categoryId)', "name": '#(categoryName)' }, "name": '#(name)', "photoUrls": '#(photoUrls)', "tags": '#(tags)', "status": '#(status)' }

    Examples:
      | id | categoryId | categoryName | name     | photoUrls            | tags       | status  |
      | 1  | 1          | 'Dogs'       | 'Rex'    | ['url1', 'url2']     | ['tag1']   | 'sold'  |
      | 2  | 2          | 'Cats'       | 'Whiskas' | ['url3', 'url4']    | ['tag2']   | 'available' |
